CREATE TABLE pairs
(
	ID INT IDENTITY (1,1) PRIMARY KEY,
	user1_ID INT NOT NULL,
	user2_ID INT NOT NULL,
	user1_decision VARCHAR(4) NOT NULL,
	user2_decision VARCHAR(4),
	match_date DATETIME2,

	CONSTRAINT fk_user1 FOREIGN KEY (user1_ID) REFERENCES users (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT fk_user2 FOREIGN KEY (user2_ID) REFERENCES users (ID) ON DELETE NO ACTION ON UPDATE NO ACTION	
)
