CREATE TABLE users_interests
(
	ID INT IDENTITY (1,1) PRIMARY KEY,
	user_id INT NOT NULL,
	interest_id INT NOT NULL,

	CONSTRAINT fk1_user FOREIGN KEY (user_id) REFERENCES users (ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk2_interest FOREIGN KEY (interest_id) REFERENCES interests (ID) ON DELETE CASCADE ON UPDATE CASCADE
)
